### ISSUE TITLE
[Runtime] Runtime info missing from Sidebar

### ISSUE THREAD

**Issue by senwang86** [codepod-io/codepod#538]
The Runtime info is missing from the Sidebar. What I did:
- Pull the latest commit
- Create a new account since DB complains that `Account not exist`
- Create a new repo and new Code pod
- No response by clicking "Create New Runtime"
- All container logs seems normal except `example-runtime-dev`.

![runtime_bug](https://github.com/codepod-io/codepod/assets/10226241/7c8bcc10-4a02-4d92-820c-99dc17936eb0)

=================================

> @codepod/runtime@1.0.0 dev /codepod/apps/runtime
> ts-node-dev src/run.ts

[INFO] 23:24:19 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 4.8.4)
Error: ZMQ_HOST not set
    at Object.<anonymous> (/codepod/apps/runtime/src/run.ts:5:9)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._compile (/codepod/node_modules/.pnpm/source-map-support@0.5.21/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-6303534930856278.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-6303534930856278.js:114:20)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-6303534930856278.js:71:20)
    at Object.nodeDevHook [as .ts] (/codepod/node_modules/.pnpm/ts-node-dev@2.0.0_@types+node@18.11.7_typescript@4.8.4/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
[ERROR] 23:24:38 Error: ZMQ_HOST not set

**Comment by lihebi** [comment]
The error in `example-runtime-dev` isn't relevant.

#528 fixed a similar behavior. Most likely, it's because your `YJS_WS_URL` didn't point to the right yjs service container. Check the logs of native-spawner and look for this:

```
console.log("connecting to y-websocket provider", yjsServerUrl);
```

see if the yjsServerUrl makes sense.

**Comment by lihebi** [comment]
I.e., the `getMyYDoc` in native spawner didn't go through. Relevant code:

https://github.com/codepod-io/codepod/blob/e7ffb0e5e6779188efd62231e6775417af0910d9/apps/spawner/src/server.ts#L33-L43

**Comment by senwang86** [comment]
Thanks for the direction. Is it due to the `web-ui` configuration in `compose.yml`, like `VITE_APP_YJS_WS_URL: ws://localhost:4233/socket`?


```
 web-ui:
    image: node:18
    working_dir: /codepod/apps/web-ui
    ports:
      - 3000:3000
    environment:
      TEST: "123"
      VITE_APP_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      VITE_APP_YJS_WS_URL: "ws://localhost:4233/socket"
      VITE_APP_API_URL: "http://localhost:4000/graphql"
      # Native spawner
      VITE_APP_SPAWNER_API_URL: "http://localhost:4022/graphql"
      # Docker spawner
      # VITE_APP_SPAWNER_API_URL: "http://localhost:4021/graphql"
    volumes:
      - ../..:/codepod
      - pnpm-store:/codepod/.pnpm-store
    command: sh -c "corepack enable && pnpm dev"
```
